config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "stweets#index"
  resources :stweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stweet.rb
class Stweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/stweets_controller.rb
class StweetsController < ApplicationController
  before_action :find_stweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @stweets = Stweet.all.order("created_at DESC")
  end

  def show
  end

  def new
    @stweet = current_user.stweets.build
  end

  def create
    @stweet = current_user.stweets.build(stweet_params)

    if @stweet.save then
      redirect_to @stweet
    else
      redirect_to "new"
    end
  end

  def edit
  end

  def update
    if @stweet.update(stweet_params) then
      flash[:notice] = "You have successfully updated your Stweet!"
      redirect_to root_path
    else
      redirect_to "edit"
    end
  end

  def destroy
    @stweet.destroy
    redirect_to root_path
  end

  private

  def stweet_params
    params.require(:stweet).permit(:stweet)
  end

  def find_stweet
    @stweet = Stweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stweets_helper.rb
module StweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav class="navbar is-info">
      <div class="navbar-brand">
        <a class="navbar-item">Stwitter</a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "Home", root_path, class: "navbar-item" %>
          <% if user_signed_in? then %>
            <%= link_to "New Stweet", new_stweet_path, class: "navbar-item" %>
          <% end %>
        </div>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if user_signed_in? then %>
              <%= link_to edit_user_registration_path, class: "button is-info" do %>
                <strong><%= current_user.name %></strong>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "button is-light is-danger" do %>
                <strong>Log Out</strong>
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, class: "button is-info" do %>
                <strong>Log In</strong>
              <% end %>
              <%= link_to new_user_registration_path, class: "button is-light is-info" do %>
                <strong>Sign Up</strong>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/stweets/_feed.html.erb
<div class="column is-half">
  <% @stweets.each do |stweet| %>
    <div class="box">
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <%= link_to stweet do %>
                <strong><%= stweet.user.name %> </strong>
              <% end %>
              <small>@<%= stweet.user.username %> 31m</small><br>
              <%= stweet.stweet %>
            </p>
          </div>
          <% if user_signed_in? %>
            <nav class="level is-mobile">
              <div class="level-left">
                <%= link_to "Edit", edit_stweet_path(stweet), class: "level-item" %>
                <%= link_to "Delete", stweet, method: :delete, class: "level-item", data: {confirm: "Are you sure you want to delete this stweet?"} %>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/stweets/_form.html.erb
<div class="section">
  <div class="container">
    <%= simple_form_for @stweet do |f| %>
      <div class="field">
        <div class="control">
          <%= f.input :stweet, label: "What's on your mind?", wrapper: false, autofocus: true, label_html: {class: "label"}, input_html: {class: "textarea"} %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.button :submit, class: "button is-info" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stweets/edit.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Edit your Stweet</h1>
    </div>
  </div>
</section>

<%= render "form" %>

app/views/stweets/index.html.erb
<div class="section">
  <div class="columns">
    <div class="column">
      <div class="box">
        <div class="level">
          <p class="image is-64x64 level-item">
              <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
          </p>
          <p class="level-item">
            <strong>Your Profile</strong><br>
            <small>@your_profile</small>
          </p>
        </div>
        <p>Your profile information will go here...</p>
      </div>
      <div class="box">
        <p><strong>Worldwide Trends</strong></p>
      </div>
    </div>
    <%= render "feed" %>
    <div class="column">
      <div class="box">
        <p><strong>People you may know..</strong></p>
      </div>
    </div>
  </div>
</div>

app/views/stweets/new.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Create a new Stweet</h1>
    </div>
  </div>
</section>

<%= render "form" %>

app/views/stweets/show.html.erb
<div class="section">
  <div class="box">
    <article class="media">
      <figure class="media-left">
        <p class="image is-64x64">
          <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= @stweet.user.name %></strong> <small>@<%= @stweet.user.username %> 31m</small><br>
            <%= @stweet.stweet %>
          </p>
        </div>
        <% if user_signed_in? %>
          <nav class="level is-mobile">
            <div class="level-left">
              <%= link_to "Edit", edit_stweet_path(@stweet), class: "level-item" %>
              <%= link_to "Delete", @stweet, method: :delete, class: "level-item", data: {confirm: "Are you sure you want to delete this stweet?"} %>
            </div>
          </nav>
        <% end %>
      </div>
    </article>
  </div>
</div>